[project]
name = "llm-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rithwik", email = "pr.rithwik.pro@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.26.0",
    "litellm>=1.99.0",
]

[project.scripts]
llm-practice = "llm_practice:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
