MODEL_GPT_4O_MINI = "openai/gpt-4o-mini"
MODEL_OLLAMA_QWEN3_4B = "ollama/qwen3:4b"
MODEL_OLLAMA_LLAMA3_2_3B = "ollama/llama3.2:3b"
MODEL_GPT_IMAGE_1_MINI = "openai/gpt-image-1-mini"
MODEL_FLUX_2_KLIEN_4B = "black-forest-labs/flux.2-klein-4b:free"
MODEL_GPT_4O_MINI_TTS = "openai/gpt-4o-mini-tts"
MODEL_OPEN_ROUTER_LLAMA_3_3_70B_INSTRUCT = "openrouter/meta-llama/llama-3.3-70b-instruct"