MODEL_GPT_4O_MINI = "gpt-4o-mini"
MODEL_OLLAMA_QWEN3_4B = "ollama/qwen3:4b"
MODEL_OLLAMA_LLAMA3_2_3B = "ollama/llama3.2:3b"
MODEL_GPT_IMAGE_1_MINI = "openai/gpt-image-1-mini"
MODEL_GPT_4O_MINI_TTS = "openai/gpt-4o-mini-tts"